/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.CategoriaDAO;
import dao.FornecedorDAO;
import dao.ProdutoDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.ObjCategoria;
import model.ObjFornecedor;
import model.ObjProduto;

/**
 *
 * @author Pichau
 */
public class FrmProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProduto
     */
    
    private boolean novo;
    private Object produto;
    private List<ObjCategoria> listaDeCategoria;
    private List<ObjFornecedor>  listaDeFornecedor;
    private ListProdutos telaListProdutos;
    
    public FrmProduto() {
        initComponents();
        carregarCategoria();
        carregarFornecedor();
        lblCodigo.setText("");
        novo = true;
    }
    
    public FrmProduto(int codigo, ListProdutos telaListProdutos) {
        initComponents();
        carregarCategoria();
        carregarFornecedor();
        novo = false;
        produto = ProdutoDAO.getProdutosByCodigo(codigo);
        carregarFormulario();
    }
    
    private void carregarFormulario(){
        ObjProduto pro = (ObjProduto) produto;
        lblCodigo.setText(String.valueOf(pro.getCodigo()));
        txtNome.setText( pro.getNome());
        txtQuantidade.setText(String.valueOf(pro.getQuantidade()));
        txtCusto.setText(String.valueOf(pro.getCusto()));
        txtPrecoDeVenda.setText(String.valueOf(pro.getPrecoDeVenda()));
        txtComentario.setText(pro.getComentario());
        
        for (int i = 1; i<listaDeCategoria.size();i++){
            ObjCategoria cat = listaDeCategoria.get(i);
            if(cat.getCodigo()== pro.getCategoria().getCodigo()){
                cmbCategoria.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 1; i<listaDeFornecedor.size();i++){
            ObjFornecedor forn = listaDeFornecedor.get(i);
            if(forn.getCodigo()== pro.getFornecedor().getCodigo()){
                cmbFornecedor.setSelectedIndex(i);
                break;
            }
        }
        if(pro.isRefrigerado()){
            rbRefrigerado.isSelected();
        }else{
            rbNaoRefrigerado.isSelected();
        }
    }
    
    private void carregarCategoria(){
        listaDeCategoria = CategoriaDAO.getCategorias();
        ObjCategoria fake  = new ObjCategoria(0, "Selecione...");
        listaDeCategoria.add( 0, fake );
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for ( ObjCategoria cat : listaDeCategoria){
            modelo.addElement(cat);
        }
        cmbCategoria.setModel(modelo);
    }
    
    private void carregarFornecedor(){
        listaDeFornecedor = FornecedorDAO.getFornecedores();
        ObjFornecedor fake = new ObjFornecedor(0,"Selecione",);
        listaDeFornecedor.add(0, fake);
        
        DefaultComboBoxModel modelo  = new DefaultComboBoxModel();
        
        for (ObjFornecedor forn : listaDeFornecedor){
            modelo.addElement(forn);
        }
        cmbFornecedor.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        armazenamento = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNome = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuantidade = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextPane();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbFornecedor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        rbRefrigerado = new javax.swing.JRadioButton();
        rbNaoRefrigerado = new javax.swing.JRadioButton();
        txtCusto = new javax.swing.JFormattedTextField();
        txtPrecoDeVenda = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Produto");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Codigo: ");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setText("000");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nome: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Fornecedor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Categoria:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Quantidade:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Custo:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Preço de Venda:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Comentario:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(txtNome);

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(txtQuantidade);

        txtComentario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(txtComentario);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cmbCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria", "Categoria 2" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        cmbFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fornecedor", "fornecedor 2" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Armazenamento:");

        armazenamento.add(rbRefrigerado);
        rbRefrigerado.setText("Refrigerado");
        rbRefrigerado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbRefrigeradoStateChanged(evt);
            }
        });

        armazenamento.add(rbNaoRefrigerado);
        rbNaoRefrigerado.setText("Não Refrigerado");

        txtCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtCusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoActionPerformed(evt);
            }
        });

        txtPrecoDeVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        txtPrecoDeVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrecoDeVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoDeVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblCodigo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar)
                            .addComponent(btnSalvar))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbRefrigerado)
                                .addGap(18, 18, 18)
                                .addComponent(rbNaoRefrigerado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecoDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCodigo))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnLimpar)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecoDeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRefrigerado)
                    .addComponent(rbNaoRefrigerado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparFormulario();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void limparFormulario(){
        txtNome.setText("");
        cmbCategoria.setSelectedIndex(0);
        cmbFornecedor.setSelectedIndex(0);
        txtQuantidade.setText("");
        txtCusto.setText("");
        txtPrecoDeVenda.setText("");
        txtComentario.setText("");
    }
    
    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void rbRefrigeradoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbRefrigeradoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRefrigeradoStateChanged

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txtNome.getText();
        ObjCategoria categoria = (ObjCategoria) cmbCategoria.getSelectedItem();
        ObjFornecedor fornecedor = (ObjFornecedor) cmbFornecedor.getSelectedItem();
        if( nome.isEmpty() || categoria.getCodigo() == 0 || fornecedor.getCodigo()==0 || !rbRefrigerado.isSelected() || !rbNaoRefrigerado.isSelected()){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatorios!");
            
        }else{
          ObjProduto pro = new ObjProduto();
          pro.setNome(nome);
          pro.setCategoria(categoria);
          pro.setFornecedor(fornecedor);
          pro.setQuantidade( Integer.valueOf(txtQuantidade.getText()));
          pro.setCusto(Integer.valueOf(txtCusto.getText()));
          pro.setPrecoDeVenda(Integer.valueOf(txtPrecoDeVenda.getText()));
          if(rbRefrigerado.isSelected()){
              pro.isRefrigerado();
          }
          pro.setComentario(txtComentario.getText());
          if( novo ){
              ProdutoDAO.inserir(pro);
          }else{
              pro.setCodigo( Integer.valueOf( lblCodigo.getText()));
              ProdutoDAO.editar(pro);
              telaListProdutos.carregarTabela( );
          }
        }
        limparFormulario();
        if( !novo ){
            this.dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    private void txtCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustoActionPerformed

    private void txtPrecoDeVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoDeVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoDeVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup armazenamento;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JRadioButton rbNaoRefrigerado;
    private javax.swing.JRadioButton rbRefrigerado;
    private javax.swing.JTextPane txtComentario;
    private javax.swing.JFormattedTextField txtCusto;
    private javax.swing.JTextPane txtNome;
    private javax.swing.JFormattedTextField txtPrecoDeVenda;
    private javax.swing.JTextPane txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
