/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Pichau
 */
public class telaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public telaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelaInicial = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastrarCategoria = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuCadastrarFornecedor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCadastrarProduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuListarCategorias = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuListarFornecedores = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuListarProdutos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuSaidaDeProdutos = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuEntradaDeProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bella Vista");

        jdpTelaInicial.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jdpTelaInicialLayout = new javax.swing.GroupLayout(jdpTelaInicial);
        jdpTelaInicial.setLayout(jdpTelaInicialLayout);
        jdpTelaInicialLayout.setHorizontalGroup(
            jdpTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jdpTelaInicialLayout.setVerticalGroup(
            jdpTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");

        menuCadastrarCategoria.setText("Categoria");
        menuCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarCategoria);
        jMenu1.add(jSeparator1);

        menuCadastrarFornecedor.setText("Fornecedor");
        menuCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarFornecedor);
        jMenu1.add(jSeparator2);

        menuCadastrarProduto.setText("Produto");
        menuCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastrarProduto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Lista");

        menuListarCategorias.setText("Categorias");
        menuListarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarCategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(menuListarCategorias);
        jMenu2.add(jSeparator3);

        MenuListarFornecedores.setText("Fornecedores");
        MenuListarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarFornecedoresActionPerformed(evt);
            }
        });
        jMenu2.add(MenuListarFornecedores);
        jMenu2.add(jSeparator4);

        menuListarProdutos.setText("Produtos");
        menuListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(menuListarProdutos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Controle de Estoque");

        menuSaidaDeProdutos.setText("Saida de Produtos");
        menuSaidaDeProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaidaDeProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(menuSaidaDeProdutos);
        jMenu3.add(jSeparator5);

        menuEntradaDeProdutos.setText("Entrada de produtos");
        menuEntradaDeProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntradaDeProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(menuEntradaDeProdutos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarCategoriaActionPerformed
        FrmCategoria Frm = new FrmCategoria();
        jdpTelaInicial.add(Frm);
        Frm.setVisible(true);
    }//GEN-LAST:event_menuCadastrarCategoriaActionPerformed

    private void menuCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarFornecedorActionPerformed
        FrmFornecedor Frm = new FrmFornecedor();
        jdpTelaInicial.add(Frm);
        Frm.setVisible(true);
    }//GEN-LAST:event_menuCadastrarFornecedorActionPerformed

    private void menuCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarProdutoActionPerformed
        FrmProduto Frm = new FrmProduto();
        jdpTelaInicial.add(Frm);
        Frm.setVisible(true);
    }//GEN-LAST:event_menuCadastrarProdutoActionPerformed

    private void menuListarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarCategoriasActionPerformed
        ListCategorias tela = new ListCategorias(jdpTelaInicial);
        jdpTelaInicial.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuListarCategoriasActionPerformed

    private void MenuListarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarFornecedoresActionPerformed
        ListFornecedores tela = new ListFornecedores(jdpTelaInicial);
        jdpTelaInicial.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_MenuListarFornecedoresActionPerformed

    private void menuListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarProdutosActionPerformed
        ListProdutos tela = new ListProdutos(jdpTelaInicial);
        jdpTelaInicial.add(tela);
        tela.setVisible(true);
    }//GEN-LAST:event_menuListarProdutosActionPerformed

    private void menuSaidaDeProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaidaDeProdutosActionPerformed
        CdeSaida Cde = new CdeSaida();
        jdpTelaInicial.add(Cde);
        Cde.setVisible(true);
    }//GEN-LAST:event_menuSaidaDeProdutosActionPerformed

    private void menuEntradaDeProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntradaDeProdutosActionPerformed
        CdeEntrada Cde = new CdeEntrada();
        jdpTelaInicial.add(Cde);
        Cde.setVisible(true);
    }//GEN-LAST:event_menuEntradaDeProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuListarFornecedores;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JDesktopPane jdpTelaInicial;
    private javax.swing.JMenuItem menuCadastrarCategoria;
    private javax.swing.JMenuItem menuCadastrarFornecedor;
    private javax.swing.JMenuItem menuCadastrarProduto;
    private javax.swing.JMenuItem menuEntradaDeProdutos;
    private javax.swing.JMenuItem menuListarCategorias;
    private javax.swing.JMenuItem menuListarProdutos;
    private javax.swing.JMenuItem menuSaidaDeProdutos;
    // End of variables declaration//GEN-END:variables
}
